version: '3.8'

services:
  view-db:
    image: mysql:8.0
    container_name: view-db
    restart: always
    environment:
      MYSQL_DATABASE: view_db
      MYSQL_USER: view_user
      MYSQL_PASSWORD: view_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - view-db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"

  view-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: view-service
    restart: always
    environment:
      DATABASE_URL: mysql+mysqlconnector://view_user:view_pass@view-db/view_db
      PASTE_SERVICE_URL: http://paste-service:5001
      ANALYTIC_SERVICE_URL: http://analytics-service:5003  # Add URL for analytics service
    depends_on:
      - view-db
    ports:
      - "5002:5002"
    volumes:
      - .:/app  # Mount current directory for live reloading/templates
    networks:
      - analytics-network
      - default


volumes:
  view-db-data:

networks:
  analytics-network:
    external: true
    name: analytics-network
