version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "5000:5000"
    environment:
      - URL_SERVICE_URL=http://url-service:5001
      - PASTE_SERVICE_URL=http://paste-service:5002
      - VIEW_SERVICE_URL=http://view-service:5003
      - ANALYTICS_SERVICE_URL=http://analytics-service:5004
      - CLEANUP_SERVICE_URL=http://cleanup-service:5005
    depends_on:
      - url-service
      - paste-service
      - view-service
      - analytics-service
      - cleanup-service

  web-ui:
    build: ./web-ui
    ports:
      - "5006:5006"
    environment:
      - API_GATEWAY_URL=http://api-gateway:5000
    depends_on:
      - api-gateway

  url-service:
    build: ./url-service
    ports:
      - "5001:5001"
    environment:
      - MYSQL_HOST=url-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=url_service
    depends_on:
      url-db:
        condition: service_healthy

  url-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=url_service
    ports:
      - "3307:3306"
    volumes:
      - ./url-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  paste-service:
    build: ./paste-service
    ports:
      - "5002:5002"

  view-service:
    build: ./view-service
    ports:
      - "5003:5003"
    environment:
      - MYSQL_HOST=view-db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=view_service
    depends_on:
      view-db:
        condition: service_healthy

  view-db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=view_service
    ports:
      - "3308:3306"
    volumes:
      - ./view-service/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s

  analytics-service:
    build: ./analytics-service
    ports:
      - "5004:5004"
    environment:
      - VIEW_SERVICE_URL=http://view-service:5003

  cleanup-service:
    build: ./cleanup-service
    ports:
      - "5005:5005"
    environment:
      - PASTE_SERVICE_URL=http://paste-service:5002
      - URL_SERVICE_URL=http://url-service:5001

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

volumes:
  url_data:
  paste_data:
  view_data:
  analytics_data:
  cleanup_data:
  grafana_data:

networks:
  pastebin-network:
    driver: bridge 