version: '3.9'

services:
  cleanup-service:
    build: .
    container_name: cleanup-service
    restart: always
    environment:
      - VIEW_SERVICE_URL=http://view-service:5002
      - PASTE_SERVICE_URL=http://paste-service:5001
      - ANALYTIC_SERVICE_URL=http://analytic-service:5003
      - CLEANUP_INTERVAL=3600
      - REQUEST_TIMEOUT=5
