version: '3.8'

services:
  analytics-db:
    image: mysql:8.0
    container_name: analytics-db
    restart: always
    environment:
      MYSQL_DATABASE: analytics_db
      MYSQL_USER: analytics_user
      MYSQL_PASSWORD: analytics_pass
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - analytics-db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"

  analytics-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytics-service
    restart: always
    environment:
      DATABASE_URL: mysql+mysqlconnector://analytics_user:analytics_pass@analytics-db/analytics_db
    depends_on:
      - analytics-db
    ports:
      - "5003:5003"
    volumes:
      - .:/app  # Mount current directory for live reloading/templates

volumes:
  analytics-db-data: