CREATE DATABASE pastebin;
GRANT ALL PRIVILEGES ON pastebin.* TO 'root'@'localhost';
FLUSH PRIVILEGES;
USE pastebin;
CREATE TABLE pastes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    expires_at DATETIME DEFAULT NULL
);
SHOW TABLES;
DESCRIBE pastes;